# Generated by Django 4.1.1 on 2022-10-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('hobby_id', models.AutoField(primary_key=True, serialize=False)),
                ('hobby_name', models.CharField(max_length=100)),
                ('hobby_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=200)),
            ],
        ),
    ]
